# Defines stages which are to be executed
stages:  
  - build
  - deploy

include:
  - local: '/.gitlab/development_ci.yml'
  - local: '/.gitlab/testing_ci.yml'
  - local: '/.gitlab/production_ci.yml'
