# Defines stages which are to be executed
stages:  
  - build
  - deploy

include:
  - remote: 'https://gitlab.consolinno-it.de/consolinno/iot-cloud-edge-embedded/edge/hems-ci/-/raw/main/nymea/development.yml'
  - local: '/.gitlab/testing_ci.yml'
  - local: '/.gitlab/production_ci.yml'
